"""Local schema catalogue — table → column list.

Add entries here to avoid TAP_SCHEMA network calls on startup.
Keys match the table name as used in ADQL FROM clauses.
"""

KNOWN_COLUMNS: dict[str, list[str]] = {
    "I/355/gaiadr3": [
        "2MASS", "2MASScoid", "A0", "AG", "AllWISE", "AllWISEoid", "And",
        "APASS9", "APASS9coid", "APF",
        "b_A0", "b_AG", "b_Dist", "b_E(BP-RP)", "b_[Fe/H]", "b_logg", "b_Teff",
        "B_A0", "B_AG", "B_Dist", "B_E(BP-RP)", "B_[Fe/H]", "B_logg", "B_Teff",
        "BP-G", "BPmag", "BP-RP",
        "chi2AL",
        "d2MASS", "dAllWISE", "dAPASS9", "dGSC23", "dHIP", "dPS1",
        "dRAVE5", "dRAVE6", "dSDSS13", "dSKYM2", "dTYC2", "dURAT1",
        "DE_ICRS", "DEJ2000", "DEPlxcor", "DEpmDEcor", "DEpmRAcor", "DEpscolCorr",
        "Dist", "DR3Name", "Dup",
        "e_BPmag", "E(BP-RP)", "E(BP/RP)", "e_DE_ICRS", "e_DEJ2000",
        "e_FBP", "e_FG", "e_FRP", "e_Gmag", "e_GRVSmag",
        "ELAT", "ELON", "EpochPh", "EpochRV",
        "e_Plx", "e_pmDE", "e_pmRA", "e_pscol", "e_RA_ICRS", "e_RAJ2000",
        "e_RPmag", "e_RV", "e_Vbroad", "epsi",
        "f_2MASS", "f_AllWISE", "f_APASS9", "f_GSC23", "f_HIP", "f_PS1",
        "f_RAVE5", "f_RAVE6", "f_SDSS13", "f_SKYM2", "f_TYC2", "f_URAT1",
        "FBP", "FG", "FRP",
        "G-RP", "Gal", "GLAT", "GLON", "Gmag", "gofAL", "GRVSmag",
        "GSC23", "GSC23coid",
        "HIP", "IPDfmp", "IPDfow", "IPDgofha", "IPDgofhp",
        "[Fe/H]",
        "Lib", "logg",
        "m2MASS", "mAllWISE", "mAPASS9", "mGSC23", "mPS1", "mSDSS13", "mSKYM2", "mURAT1",
        "MatchObs", "MatchObsA", "MatchObsrm", "MCMCGSP", "MCMCMSC", "Mode",
        "n2MASS", "nAllWISE", "nAPASS9", "nGSC23", "nHIP", "nPS1",
        "nRAVE5", "nRAVE6", "nSDSS13", "nSKYM2", "nTYC2", "nURAT1",
        "n_RV", "NAC", "NAL", "NbAL", "NBPblend", "NBPcont",
        "NewMatchObs", "NgAL", "Nper", "NRPblend", "NRPcont", "NSS",
        "nueff",
        "o_BPmag", "o_Gmag", "o_GRVSmag", "o_RPmag", "o_RV", "o_RVd", "o_Vbroad",
        "PGal", "Plx", "PlxpmDEcor", "PlxpmRAcor", "PlxpscolCorr",
        "PM", "pmDE", "pmDEpscolCorr", "pmRA", "pmRApmDEcor", "pmRApscolCorr",
        "PQSO", "PS1", "PS1coid", "pscol", "PSS",
        "QSO",
        "RA_ICRS", "RAJ2000", "RADEcor", "RADEcorJ2000", "RandomI",
        "RAPlxcor", "RApmDEcor", "RApmRAcor", "RApscolCorr",
        "RAVE5", "RAVE5coid", "RAVE6", "RAVE6oid",
        "RFBP", "RFG", "RFRP", "RPlx", "RPmag", "RUWE",
        "RV", "RVamp", "RVchi2", "RVgof", "RVNper", "RVS", "RVS/N", "RVSS/N",
        "RVTdur", "RVtemp[Fe/H]", "RVtemplogg", "RVtempTeff",
        "SDMk1", "SDMk2", "SDMk3", "SDMk4",
        "SDSS13", "SDSS13coid", "SDSk1", "SDSk2", "SDSk3", "SDSk4",
        "sepsi", "SKYM2", "SolID", "Solved", "Source",
        "Teff", "TYC2", "TYC2moid",
        "URAT1", "URAT1oid",
        "VarFlag", "Vatmparam", "Vbroad",
        "XPcont", "XPsamp",
        "amax",
    ],
}
